function preproc_report(info, report_dir)
% generate a .tex report based on preprocessing data
% based on function from FP
prepTimeInfo = ['Time elapsed:  ',num2str(info.time)  '\\\\ \n'];

rawDataInformation = ...
    ['Subject ID: ', info.subject_id, '\n', ...
    '\\\\ Original sampling frequency: ', num2str(info.orig_sf),' \n',...
    '\\\\ Original data length in mins: ', num2str(info.minutes),' \n',...
    '\\\\ Number of channels: ', num2str(info.nchan),' \n',...
    ];

filteringInformation = ['\\\\ Low pass filter cut-off: ', num2str(info.freq),'\n',...
    '\\\\ Bandstop filter: ', num2str(info.bsfreq),'\n',...
    ];

downsamplingInformation = ['\\\\ Original sampling frequency: ', num2str(info.orig_sf),'\n',...
    '\\\\ New sampling frequency: ', num2str(info.fs),'\n',...
    ];

epochingInformation = ['Number of trials: ', num2str(info.ntri),' \n',...
    '\\\\ Trial  length in seconds: ', num2str(info.nsam),' \n',...
    '\\\\ Pre-stimulus time: ', num2str(info.prestim),' \n',...
    '\\\\ Post-stimulus time: ', num2str(info.poststim),' \n',...
    ];

%rejectedChanLabels = info.prep.chanLabels(info.outlier.chanRejectFinal');

chanEpochRejection = ['Number of rejected channels: ', num2str(length(info.badchans)),' \n',...
    '\\\\ Indices of rejected channels: ', num2str(reshape(info.badchans,1,[])),' \n',...
    '\\\\ Number of rejected epochs: ', num2str(length(info.badtrials)),' \n',...
    '\\\\ Indices of rejected epochs: ', num2str(reshape(info.badtrials,1,[])),'\\\\ \n',...
    '\\\\ Percentage of rejected epochs: ', num2str(info.prcbadtri),'\\\\ \n',...
    ];

chanInterpolation = ['Number of interpolated channels: ', num2str(length(info.badchans)),' \n',...
    '\\\\ Indices of Interpolated channels: ', num2str(reshape(info.badchans,1,[])),' \n',...
    ];

spectraPlots = [
   '\\subsection*{ Spectra plots and topoplots:}\n',...
   '\\subsubsection*{After preprocessing}\n',...
    '\\includegraphics[width=14cm]{spectrum_after.jpg}\\\\\n',...
    '\\includegraphics[width=14cm]{topo_after.jpg}\\\\\n',...
    ];

fileID = fopen([report_dir,'report.tex'],'w');

fprintf(fileID, ['\\documentclass[10pt,a4paper,oneside]{report}\n',...
'\\usepackage{helvet}\n',...
'\\usepackage{helvet}\n',...
'\\usepackage{tgbonum}\n',...
'\\renewcommand{\\familydefault}{\\sfdefault}\n',...
'\\usepackage{array,booktabs}\n',...
'\\usepackage{amsmath}\n',...
'\\usepackage{setspace}\n',...
'\\usepackage{rotating}\n',...
'\\usepackage{color}\n',...
'\\usepackage{multirow}\n',...
'\\usepackage{nth}\n',...
'\\usepackage{graphicx}\n',...
'\\usepackage[font=scriptsize]{caption}\n',...
'\\usepackage[font=scriptsize]{subcaption}\n',...
'\\usepackage{natbib}\n',...
'\\usepackage{geometry}\n',...
'\\usepackage{hyperref}\n',...
'\\geometry{\n',...
	'a4paper,',...
	'total={210mm,297mm},\n',...
	'left=17mm,\n',...
	'right=17mm,\n',...
	'top=20mm,\n',...
	'bottom=20mm,\n',...
'}',...
'\\newcommand*\\rot{\\rotatebox{90}}\n',...
'\\newcommand\\norm[1]{\\left\\lVert#1\\right\\rVert}\n',...
'\\begin{document}\n',...
	'\\author{Veronika Shamova}\n',...
    '\\date{\\taday}\n',...
    '\\section*{Preprocessing report:}\n',...
    prepTimeInfo,...
    '\\subsection*{1. Data information:}\n',...
    rawDataInformation,...
    '\\subsection*{2. Filtering:}\n',...
    filteringInformation,...
    '\\subsection*{3. Downsampling:}\n',...
    downsamplingInformation,...
    '\\subsection*{4. Epoching:}\n',...
    epochingInformation,...
    '\\subsection*{5. Outlier epoch/channel rejection:}\n',...
    chanEpochRejection,...
    '\\includegraphics[width=14cm]{bad_channels.png}\\\\\n',...
    '\\includegraphics[width=14cm]{bad_trials.png}\\\\\n',...
   '\\subsection*{7. Channel interpolation:}\n',...
   chanInterpolation,...
    spectraPlots,...
    '\\end{document}\n',...
]);
fclose(fileID);
disp(['Output file is saved in:', report_dir]);
end
